name: Deploy Chrome VM

on: [workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy VM with Terraform
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve

  destroy:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Destroy VM
        run: |
          cd terraform
          terraform destroy -auto-approve
