name: Deploy Ubuntu VM with Chrome, xRDP, and NoMachine

on: [workflow_dispatch]

jobs:
  deploy:
    name: Deploy and Configure VM
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create Resource Group and VM
      run: |
        RESOURCE_GROUP=chrome-vm-gh
        VM_NAME=chrome-ubuntu-vm
        LOCATION=westeurope
        ADMIN_USER=azureuser
        ADMIN_PASS='YourPassword123!'

        # Create Resource Group
        az group create --name $RESOURCE_GROUP --location $LOCATION

        # Create VM with Ubuntu 22.04 and run install script
        az vm create \
          --resource-group $RESOURCE_GROUP \
          --name $VM_NAME \
          --image Canonical:0001-com-ubuntu-server-jammy:22_04-lts-gen2:latest \
          --admin-username $ADMIN_USER \
          --admin-password $ADMIN_PASS \
          --size Standard_B2s \
          --authentication-type password \
          --custom-data install_desktop.sh \
          --output none

        # Open RDP and NoMachine ports
        az vm open-port --resource-group $RESOURCE_GROUP --name $VM_NAME --port 3389 --priority 1001
        az vm open-port --resource-group $RESOURCE_GROUP --name $VM_NAME --port 4000 --priority 1002

    # Optional Cleanup
    # You can comment this out during testing
#   cleanup:
#     name: Cleanup Resources
#     needs: deploy
#     runs-on: ubuntu-latest
#     if: always()

#     steps:
#     - name: Azure Login
#       uses: azure/login@v1
#       with:
#         creds: ${{ secrets.AZURE_CREDENTIALS }}

#     - name: Delete Resource Group
#       run: |
#         az group delete --name chrome-vm-gh --yes --no-wait
