name: Deploy VM (Ubuntu or Windows)

on:
  workflow_dispatch:
    inputs:
      create_linux:
        description: "Create Linux VM"
        required: true
        default: "true"
      create_windows:
        description: "Create Windows VM"
        required: true
        default: "false"
      resource_group_n:
        description: "Azure Resource Group Name"
        required: true
        default: "chrome-vm-gh"
      location_n:
        description: "Azure Region"
        required: true
        default: "westeurope"

jobs:
  deploy:
    name: Deploy Selected VM
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create Resource Group
      run: |
        az group create --name ${{ vars.AZURE_RG }} --location ${{ vars.AZURE_LOCATION }}

    - name: Deploy Linux VM
      if: ${{ github.event.inputs.create_linux == 'true' }}
      run: |
        RESOURCE_GROUP=${{ vars.AZURE_RG }}
        LOCATION=${{ vars.AZURE_LOCATION }}
        VM_NAME=${{ vars.VM_NAME }}
        ADMIN_USER=${{ vars.VM_USER }}
        ADMIN_PASS=${{ secrets.VM_PASS}}

        echo "Deploying Linux VM..."

        az vm create \
          --resource-group $RESOURCE_GROUP \
          --name $VM_NAME \
          --image Canonical:0001-com-ubuntu-server-jammy:22_04-lts-gen2:latest \
          --admin-username $ADMIN_USER \
          --admin-password $ADMIN_PASS \
          --size Standard_B2s \
          --authentication-type password \
          --custom-data install_desktop.sh \
          --location $LOCATION \
          --output none

        az vm open-port --resource-group $RESOURCE_GROUP --name $VM_NAME --port 3389 --priority 1001
        az vm open-port --resource-group $RESOURCE_GROUP --name $VM_NAME --port 4000 --priority 1002

    - name: Deploy Windows VM
      if: ${{ github.event.inputs.create_windows == 'true' }}
      run: |
        RESOURCE_GROUP=${{ vars.AZURE_RG }}
        LOCATION=${{ vars.AZURE_LOCATION }}
        VM_NAME=${{ vars.VM_NAME_W }}
        ADMIN_USER=${{ vars.VM_USER }}
        ADMIN_PASS=${{ secrets.VM_PASS}}
        VM_SIZE=${{ vars.VM_SIZE_W }}

        echo "Deploying Windows VM..."

        az vm create \
          --resource-group $RESOURCE_GROUP \
          --name $VM_NAME \
          --image MicrosoftWindowsServer:WindowsServer:2022-datacenter-g2:latest \
          --admin-username $ADMIN_USER \
          --admin-password $ADMIN_PASS \
          --size $VM_SIZE \
          --authentication-type password \
          --location $LOCATION \
          --output none

        az vm open-port --resource-group $RESOURCE_GROUP --name $VM_NAME --port 3389 --priority 1001
