name: Deploy VM (Ubuntu or Windows)

on:
  workflow_dispatch:
    inputs:
      create_linux:
        description: "Create Linux VM"
        required: true
        default: "true"
      create_windows:
        description: "Create Windows VM"
        required: true
        default: "false"
      resource_group_n:
        description: "Azure Resource Group Name"
        required: true
        default: "chrome-vm-gh"
      location_n:
        description: "Azure Region"
        required: true
        default: "centralindia"

jobs:
  deploy:
    name: Deploy Selected VM
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set Variables
      run: |
        echo "RESOURCE_GROUP=${{ github.event.inputs.resource_group_n }}" >> $GITHUB_ENV
        echo "LOCATION=${{ github.event.inputs.location_n }}" >> $GITHUB_ENV
        echo "VM_USER=azureuser" >> $GITHUB_ENV
        echo "VM_PASS=${{ secrets.VM_PASS }}" >> $GITHUB_ENV
        echo "LINUX_VM_NAME=linux-gh-vm" >> $GITHUB_ENV
        echo "WINDOWS_VM_NAME=windows-gh-vm" >> $GITHUB_ENV
        echo "WINDOWS_VM_SIZE=Standard_D4s_v3" >> $GITHUB_ENV

    - name: Create Resource Group
      run: |
        az group create --name $RESOURCE_GROUP --location $LOCATION

    - name: Deploy Linux VM
      if: ${{ github.event.inputs.create_linux == 'true' }}
      run: |
        echo "Deploying Linux VM..."

        az vm create \
          --resource-group $RESOURCE_GROUP \
          --name $LINUX_VM_NAME \
          --image Canonical:0001-com-ubuntu-server-jammy:22_04-lts-gen2:latest \
          --admin-username $VM_USER \
          --admin-password "$VM_PASS" \
          --size Standard_B2s \
          --authentication-type password \
          --custom-data install_desktop.sh \
          --location $LOCATION \
          --output none

        az vm open-port --resource-group $RESOURCE_GROUP --name $LINUX_VM_NAME --port 3389 --priority 1001
        az vm open-port --resource-group $RESOURCE_GROUP --name $LINUX_VM_NAME --port 4000 --priority 1002

    - name: Deploy Windows VM
      if: ${{ github.event.inputs.create_windows == 'true' }}
      run: |
        echo "Deploying Windows VM..."

        az vm create \
          --resource-group $RESOURCE_GROUP \
          --name $WINDOWS_VM_NAME \
          --image MicrosoftWindowsServer:WindowsServer:2022-datacenter-g2:latest \
          --admin-username $VM_USER \
          --admin-password "$VM_PASS" \
          --size $WINDOWS_VM_SIZE \
          --authentication-type password \
          --location $LOCATION \
          --output none

        az vm open-port --resource-group $RESOURCE_GROUP --name $WINDOWS_VM_NAME --port 3389 --priority 1001
