name: Destory VM Workflow

on: [workflow_dispatch]

jobs:
  cleanup:
    name: Cleanup Resources
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Delete Resource Group
      run: |
        RESOURCE_GROUP=${{ vars.AZURE_RG }}

        az group delete --name $RESOURCE_GROUP --yes --no-wait
